### ISSUE TITLE
Device Query error - reason: 'INVALID_PARAMETER', parameter: 'nodeId' 

### ISSUE THREAD

**Issue by travellingnashes** [aklambeth/bg-hive-api#1]
On querying the connection.command.push(getDeviceTask,  for hotwater or climate I get the error code : 'INVALID_PARAMETER', parameter: 'nodeId' 

Where is nodeId coming from as I cannot see it in the definition. Is anyone else seeing this. This is a new device installed by British gas yesterday. States version 2 on the hub

**Comment by aklambeth** [comment]
Thanks for logging this and bringing it to my attention, sorry it took a while. It looks like there were some breaking changes made to the API. I've fixed this in the current release 1.0.3. You will be able to get this via NPM.

**Comment by travellingnashes** [comment]
Perfect thanks for the update. Im bolting it onto HomeKit if you are interested
